name: GitHub Webhook Trigger

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Webhook
      run: |
        curl -X POST https://48540cd18b75.ngrok-free.app/webhook \
        -H "Content-Type: application/json" \
        -d '{
          "request_id": "${{ github.sha }}",
          "author": "${{ github.actor }}",
          "action": "${{ github.event_name }}",
          "from_branch": "${{ github.head_ref || github.ref }}",
          "to_branch": "${{ github.base_ref || github.ref }}",
          "timestamp": "${{ github.event.head_commit.timestamp || github.event.pull_request.updated_at }}"
        }'
